const KEY='vinicius-crud-demo-v1';
const seed=[{id:crypto.randomUUID(),nome:'Marina Costa',nascimento:'1998-05-14',telefone:'(35) 99921-4810',email:'marina@example.com',endereco:'Lavras - MG',servico:'Corte'},{id:crypto.randomUUID(),nome:'Lucas Almeida',nascimento:'2001-11-02',telefone:'(31) 98844-1207',email:'lucas@example.com',endereco:'Belo Horizonte - MG',servico:'Barba'}];
let clients=JSON.parse(localStorage.getItem(KEY)||'null')||seed;
const $=id=>document.getElementById(id);const form=$('clientForm');
function save(){localStorage.setItem(KEY,JSON.stringify(clients));render()}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function date(v){if(!v)return '—';const [y,m,d]=v.split('-');return `${d}/${m}/${y}`}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function render(){const q=$('search').value.trim().toLowerCase();const filtered=clients.filter(c=>Object.values(c).some(v=>String(v).toLowerCase().includes(q)));$('total').textContent=clients.length;$('comEmail').textContent=clients.filter(c=>c.email).length;$('comTelefone').textContent=clients.filter(c=>c.telefone).length;$('empty').classList.toggle('hidden',filtered.length>0);$('clientRows').innerHTML=filtered.map(c=>`<tr><td><div class="name">${esc(c.nome)}</div><div class="muted">${esc(c.endereco||'Endereço não informado')}</div></td><td>${esc(c.telefone||'—')}<div class="muted">${esc(c.email||'Sem e-mail')}</div></td><td>${esc(c.servico||'—')}</td><td>${date(c.nascimento)}</td><td><button class="action edit" data-edit="${c.id}">Editar</button><button class="action delete" data-delete="${c.id}">Excluir</button></td></tr>`).join('')}
function resetForm(){form.reset();$('editId').value='';$('formTitle').textContent='Novo cliente';$('submitText').textContent='Cadastrar cliente';$('cancelEdit').classList.add('hidden')}
form.addEventListener('submit',e=>{e.preventDefault();const id=$('editId').value;const data={id:id||crypto.randomUUID(),nome:$('nome').value.trim(),nascimento:$('nascimento').value,telefone:$('telefone').value.trim(),email:$('email').value.trim(),endereco:$('endereco').value.trim(),servico:$('servico').value.trim()};if(id){clients=clients.map(c=>c.id===id?data:c);toast('Cliente atualizado')}else{clients.unshift(data);toast('Cliente cadastrado')}save();resetForm()});
$('clientRows').addEventListener('click',e=>{const edit=e.target.dataset.edit,del=e.target.dataset.delete;if(edit){const c=clients.find(x=>x.id===edit);if(!c)return;$('editId').value=c.id;$('nome').value=c.nome;$('nascimento').value=c.nascimento;$('telefone').value=c.telefone;$('email').value=c.email;$('endereco').value=c.endereco;$('servico').value=c.servico;$('formTitle').textContent='Editar cliente';$('submitText').textContent='Salvar alterações';$('cancelEdit').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}if(del&&confirm('Excluir este cliente da demonstração?')){clients=clients.filter(c=>c.id!==del);save();toast('Cliente excluído')}});
$('cancelEdit').addEventListener('click',resetForm);$('search').addEventListener('input',render);$('clearAll').addEventListener('click',()=>{if(confirm('Limpar todos os dados desta demonstração?')){clients=[];save();resetForm();toast('Demonstração limpa')}});save();